baseurl = "https://tenzer.dk/"
title = "Tenzer.dk"
disableKinds = ["404"]

[permalinks]
post = "/:title/"

[taxonomies]

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = false
